name: Deploy site to GitHub Pages

on:
  push:
    branches: ["main"]

env:
  PUBLISH_DIR: . # Altere para ./public ou ./dist conforme seu projeto
  BUILD_CMD: ""  # Deixe vazio se não precisa de build, ou use "npm install && npm run build"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build site (if needed)
        if: env.BUILD_CMD != ''
        run: ${{ env.BUILD_CMD }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site content
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
